# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(max_length=200, null=True)),
                ('add_post', models.TextField(max_length=2500, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_cat', to='advert.Category')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_subcat', to='advert.SubCategory')),
            ],
        ),
    ]
