# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_auto_20180313_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_pa', to='advert.Category'),
            preserve_default=False,
        ),
    ]
