# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20180313_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_p', to='advert.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='postadd',
            name='category',
        ),
        migrations.AddField(
            model_name='postadd',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory_p', to='advert.SubCategory'),
            preserve_default=False,
        ),
    ]
