# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0010_auto_20180313_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
